"""Generate a reproducible notebook for a trained model."""
from __future__ import annotations

import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook


def notebook(meta: dict) -> str:
    task = meta["task"]; target = meta["target"]
    prep = meta.get("prep_options") or {}
    scaler = {"standard": "StandardScaler()", "minmax": "MinMaxScaler()", "robust": "RobustScaler()", "none": None}.get(prep.get("scaler", "standard"))
    enc = "OneHotEncoder(handle_unknown='ignore', sparse_output=False)" if prep.get("encoder", "onehot") == "onehot" else "OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)"
    num_steps = f"[('impute', SimpleImputer(strategy='{prep.get('num_impute', 'median')}'))" + (f", ('scale', {scaler})" if scaler else "") + "]"
    cells = [
        new_markdown_cell(f"# {meta['name']}\n\nGenerated by ML Help. Task: **{task}**, target: `{target}`.\n\nThe pipeline below is the exact structure that was trained in the app. Point `df` at your file and run top to bottom."),
        new_code_cell("import pandas as pd\nimport numpy as np\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.impute import SimpleImputer\nfrom sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, OneHotEncoder, OrdinalEncoder\nfrom sklearn.model_selection import train_test_split, cross_val_score\n" + meta.get("imports", "")),
        new_code_cell(f"df = pd.read_csv('your_dataset.csv')\ntarget = '{target}'\nfeatures = {meta['features']!r}\nX = df[features]\ny = df[target]"),
        new_markdown_cell("## Preprocessing\n\nNumeric columns are imputed and scaled; text columns are imputed and encoded. The transformer is fitted on training rows only, inside the pipeline, so nothing leaks from the test set."),
        new_code_cell(f"numeric = {meta['numeric']!r}\ncategorical = {meta['categorical']!r}\npreprocessor = ColumnTransformer([\n    ('num', Pipeline({num_steps}), numeric),\n    ('cat', Pipeline([('impute', SimpleImputer(strategy='{prep.get('cat_impute', 'most_frequent')}', fill_value='missing')), ('encode', {enc})]), categorical),\n])"),
        new_markdown_cell("## Model"),
        new_code_cell(f"model = {meta['estimator_code']}\npipe = Pipeline([('prep', preprocessor), ('model', model)])"),
        new_markdown_cell("## Train and evaluate"),
        new_code_cell(f"X_train, X_test, y_train, y_test = train_test_split(X, y, test_size={meta.get('test_size', 0.2)}, random_state=42{', stratify=y' if task == 'classification' else ''})\npipe.fit(X_train, y_train)\nprint('test score:', pipe.score(X_test, y_test))\nprint('cv scores:', cross_val_score(pipe, X, y, cv=3))"),
    ]
    nb = new_notebook(cells=cells, metadata={"kernelspec": {"name": "python3", "display_name": "Python 3"}})
    return nbformat.writes(nb)
