GLOSSARY = [
    {"term": "Supervised learning", "text": "Learning from examples that come with the right answer. Classification predicts a label; regression predicts a number."},
    {"term": "Unsupervised learning", "text": "Finding structure in data that has no answer column: clusters, compressed representations, outliers."},
    {"term": "Feature", "text": "One input column. Features are what the model looks at."},
    {"term": "Target / label", "text": "The column the model learns to predict."},
    {"term": "Train / test split", "text": "Hold back a slice of rows the model never trains on, so the score reflects new data instead of memory."},
    {"term": "Cross-validation", "text": "Cut the data into k folds; each fold takes a turn as the test set. The average score is far more reliable than one split."},
    {"term": "Stratified", "text": "A split that keeps each class's proportion the same in train and test."},
    {"term": "Data leakage", "text": "Any information from the test rows reaching the model during training, including fitting a scaler on all rows. Makes scores look better than reality."},
    {"term": "Overfitting", "text": "The model memorizes the training rows, including their noise. Symptom: high train score, much lower test score."},
    {"term": "Underfitting", "text": "The model is too simple to capture the pattern. Symptom: low train and test scores."},
    {"term": "Bias / variance", "text": "Bias is error from a model too rigid to fit the truth. Variance is error from a model so flexible it chases noise. Ensembles mostly fight variance; boosting also lowers bias."},
    {"term": "Hyperparameter", "text": "A setting you choose before training (tree depth, k in KNN, C in SVM), as opposed to parameters the model learns."},
    {"term": "Grid search / random search", "text": "Try many hyperparameter combinations and keep the best by cross-validation. Random search covers the space better per fit."},
    {"term": "Regularization", "text": "A penalty that keeps a model simpler: smaller weights, shallower trees. The main lever against overfitting."},
    {"term": "Scaling / standardization", "text": "Rescale each numeric column so they share a range. Essential for distance-based and gradient-based models; irrelevant for trees."},
    {"term": "One-hot encoding", "text": "Turn a text column into one 0/1 column per category, so no false ordering is implied."},
    {"term": "Imputation", "text": "Filling missing values with a statistic (median, most frequent) or a constant."},
    {"term": "Ensemble", "text": "Several models combined into one predictor. Bagging averages independent models; boosting chains them; voting and stacking mix different model types."},
    {"term": "Bagging", "text": "Bootstrap aggregating: train copies of a model on random resamples and average. Random Forest is bagging of trees."},
    {"term": "Boosting", "text": "Train weak models in sequence, each correcting the previous ones. AdaBoost, Gradient Boosting, XGBoost, LightGBM."},
    {"term": "Stacking", "text": "Base models' predictions become the inputs of a final model that learns how to weigh them."},
    {"term": "Confusion matrix", "text": "A table of true class versus predicted class. The diagonal is right; off-diagonal cells name the mistakes."},
    {"term": "Precision", "text": "Of everything flagged positive, the share that truly was. High precision means few false alarms."},
    {"term": "Recall", "text": "Of everything truly positive, the share that was caught. High recall means few misses."},
    {"term": "F1", "text": "Harmonic mean of precision and recall; a single number that drops if either is poor."},
    {"term": "ROC AUC", "text": "How well the model ranks positives above negatives across all thresholds. 0.5 is random, 1.0 is perfect."},
    {"term": "R2", "text": "Share of the target's variance explained by the model. 1 is perfect, 0 is no better than the mean."},
    {"term": "RMSE / MAE", "text": "Typical size of a regression miss in target units. RMSE punishes large misses more."},
    {"term": "Learning curve", "text": "Score versus training-set size. Shows whether more data would help (curves still rising) or not (converged)."},
    {"term": "Feature importance", "text": "How much each feature contributes. Impurity-based for trees, coefficients for linear models, permutation for anything."},
    {"term": "Silhouette score", "text": "How well each row fits its cluster versus the next nearest cluster, from -1 to 1."},
    {"term": "Inertia / elbow", "text": "KMeans' within-cluster spread. Plot it against k and pick the bend where adding clusters stops paying off."},
    {"term": "PCA", "text": "Principal component analysis: new axes ordered by variance explained. Compresses many correlated columns into a few."},
    {"term": "Pipeline", "text": "A sklearn object that chains preprocessing and model so they fit together and leakage is impossible by construction."},
]
